import type { GymLevel, HabitEntry, PersonalizationTag } from "./types";

type HabitTemplate = {
  id: string;
  title: string;
  description: string;
  category: HabitEntry["category"];
  baseDifficulty: HabitEntry["difficulty"];
  baseDuration: number;
  baseXp: number;
  icon: string;
  evidenceLevel: HabitEntry["evidenceLevel"];
  tags: PersonalizationTag[];
  gymLevel: GymLevel;
};

const WEEK_VARIANTS = [
  { weekMin: 1, label: "Basis", durationFactor: 1, xpBonus: 0, difficultyDelta: 0 },
  { weekMin: 2, label: "Aufbau", durationFactor: 1.15, xpBonus: 5, difficultyDelta: 0 },
  { weekMin: 3, label: "Progression", durationFactor: 1.3, xpBonus: 10, difficultyDelta: 1 },
  { weekMin: 4, label: "Intensiv", durationFactor: 1.45, xpBonus: 15, difficultyDelta: 1 },
] as const;

const DIFFICULTY_ORDER: HabitEntry["difficulty"][] = ["leicht", "mittel", "schwer"];

const getProgressedDifficulty = (
  baseDifficulty: HabitEntry["difficulty"],
  delta: number,
): HabitEntry["difficulty"] => {
  const baseIndex = DIFFICULTY_ORDER.indexOf(baseDifficulty);
  const nextIndex = Math.min(DIFFICULTY_ORDER.length - 1, Math.max(0, baseIndex + delta));
  return DIFFICULTY_ORDER[nextIndex];
};

const HABIT_TEMPLATES: HabitTemplate[] = [
  {
    id: "chin-tucks",
    title: "Chin Tucks 3x12",
    description: "Kinn kontrolliert nach hinten ziehen, um tiefe Nackenflexoren zu aktivieren und Forward-Head-Haltung zu reduzieren.",
    category: "haltung",
    baseDifficulty: "leicht",
    baseDuration: 6,
    baseXp: 24,
    icon: "align-center",
    evidenceLevel: "evidenzbasiert",
    tags: ["haltung", "kinn", "harmonie"],
    gymLevel: "alle",
  },
  {
    id: "wall-slides",
    title: "Wall Slides 3x10",
    description: "Ruecken und Arme an der Wand halten, um Schulterblattkontrolle und aufrechte Thoraxposition zu trainieren.",
    category: "haltung",
    baseDifficulty: "leicht",
    baseDuration: 7,
    baseXp: 26,
    icon: "panel-top",
    evidenceLevel: "evidenzbasiert",
    tags: ["haltung", "symmetrie", "praesentation"],
    gymLevel: "alle",
  },
  {
    id: "face-pulls-band",
    title: "Face Pulls mit Band 4x15",
    description: "Ellbogen hoch fuehren und Schulterblaetter nach hinten unten setzen fuer stabile Schultern und bessere Haltung.",
    category: "haltung",
    baseDifficulty: "mittel",
    baseDuration: 9,
    baseXp: 34,
    icon: "cable",
    evidenceLevel: "evidenzbasiert",
    tags: ["haltung", "symmetrie", "praesentation"],
    gymLevel: "fortgeschritten",
  },
  {
    id: "thoracic-extensions-foamroll",
    title: "Thoracic Extensions auf Rolle 3x10",
    description: "Brustwirbelsaeule ueber Foam Roller bewegen, um Rundruecken durch langes Sitzen auszugleichen.",
    category: "haltung",
    baseDifficulty: "mittel",
    baseDuration: 8,
    baseXp: 31,
    icon: "waves",
    evidenceLevel: "evidenzbasiert",
    tags: ["haltung", "praesentation", "harmonie"],
    gymLevel: "alle",
  },
  {
    id: "doorway-stretch-90-90",
    title: "Doorway Stretch 2x60s",
    description: "Brust im Tuerrahmen oeffnen, um nach vorn gezogene Schultern zu entlasten.",
    category: "haltung",
    baseDifficulty: "leicht",
    baseDuration: 6,
    baseXp: 22,
    icon: "door-open",
    evidenceLevel: "evidenzbasiert",
    tags: ["haltung", "praesentation"],
    gymLevel: "alle",
  },
  {
    id: "scapular-retractions-hold",
    title: "Scapular Retractions 4x12",
    description: "Schulterblaetter fuer 2 Sekunden aktiv zusammenziehen, um oberen Ruecken neuromuskulaer zu staerken.",
    category: "haltung",
    baseDifficulty: "leicht",
    baseDuration: 7,
    baseXp: 25,
    icon: "shrink",
    evidenceLevel: "evidenzbasiert",
    tags: ["haltung", "symmetrie"],
    gymLevel: "alle",
  },
  {
    id: "ytwl-series",
    title: "YTWL Serie 3 Runden",
    description: "Y-T-W-L Bewegungen in sauberer Technik fuer Rotatorenmanschette und Schulterblattstabilitaet.",
    category: "haltung",
    baseDifficulty: "mittel",
    baseDuration: 10,
    baseXp: 36,
    icon: "move-up-right",
    evidenceLevel: "evidenzbasiert",
    tags: ["haltung", "symmetrie", "praesentation"],
    gymLevel: "fortgeschritten",
  },
  {
    id: "band-pull-apart-20",
    title: "Band Pull Apart 4x20",
    description: "Band auf Brusthoehe auseinanderziehen, um hintere Schulter und Haltungsmuskulatur zu kraeftigen.",
    category: "haltung",
    baseDifficulty: "mittel",
    baseDuration: 8,
    baseXp: 33,
    icon: "move-horizontal",
    evidenceLevel: "evidenzbasiert",
    tags: ["haltung", "praesentation"],
    gymLevel: "alle",
  },
  {
    id: "farmer-carry-2x40m",
    title: "Farmer Carries 4x40m",
    description: "Schwere Last mit neutraler Wirbelsaeule tragen, um Griff, Core und aufrechte Haltung zu verbessern.",
    category: "haltung",
    baseDifficulty: "mittel",
    baseDuration: 11,
    baseXp: 40,
    icon: "briefcase",
    evidenceLevel: "evidenzbasiert",
    tags: ["haltung", "praesentation", "koerperfett"],
    gymLevel: "fortgeschritten",
  },
  {
    id: "neck-mobility-flow",
    title: "Neck Mobility Flow 2x5 Min",
    description: "Langsame Flexion, Rotation und Seitneigung zur Erhaltung der Nackenbeweglichkeit ohne Schmerzprovokation.",
    category: "haltung",
    baseDifficulty: "leicht",
    baseDuration: 8,
    baseXp: 24,
    icon: "rotate-cw",
    evidenceLevel: "evidenzbasiert",
    tags: ["haltung", "kinn", "harmonie"],
    gymLevel: "alle",
  },
  {
    id: "upper-trap-stretch-60s",
    title: "Upper Trap Stretch 3x60s",
    description: "Kopf zur Seite neigen und obere Trapezmuskulatur ruhig dehnen, um Spannung nach Bildschirmarbeit zu senken.",
    category: "haltung",
    baseDifficulty: "leicht",
    baseDuration: 6,
    baseXp: 21,
    icon: "stretch-horizontal",
    evidenceLevel: "evidenzbasiert",
    tags: ["haltung", "schlaf"],
    gymLevel: "alle",
  },
  {
    id: "pec-stretch-corner",
    title: "Pec Stretch in Ecke 2x75s",
    description: "Brustfasern in der Ecke dehnen, um Schulterinnenrotation und Rundschulter zu reduzieren.",
    category: "haltung",
    baseDifficulty: "leicht",
    baseDuration: 7,
    baseXp: 22,
    icon: "corner-up-left",
    evidenceLevel: "evidenzbasiert",
    tags: ["haltung", "praesentation"],
    gymLevel: "alle",
  },
  {
    id: "deep-neck-flexor-hold",
    title: "Deep Neck Flexor Hold 4x30s",
    description: "In Rueckenlage Kinn leicht einziehen und Position halten, um tiefe Halsbeuger gezielt aufzubauen.",
    category: "haltung",
    baseDifficulty: "mittel",
    baseDuration: 9,
    baseXp: 34,
    icon: "timer",
    evidenceLevel: "evidenzbasiert",
    tags: ["haltung", "kinn", "harmonie"],
    gymLevel: "alle",
  },
  {
    id: "deep-neck-flexor-march",
    title: "Deep Neck Flexor March 3x12",
    description: "Aus dem Chin-Tuck kurze kontrollierte Kopfhebungen ausfuehren, um Haltekraft unter Bewegung zu trainieren.",
    category: "haltung",
    baseDifficulty: "mittel",
    baseDuration: 9,
    baseXp: 35,
    icon: "activity",
    evidenceLevel: "evidenzbasiert",
    tags: ["haltung", "kinn", "praesentation"],
    gymLevel: "fortgeschritten",
  },
  {
    id: "upper-body-push-4x8",
    title: "Upper Body Push 4x8 (Bank + OHP)",
    description: "Kombination aus horizontalem und vertikalem Druecken fuer Brust, Schulter und Trizeps.",
    category: "gym",
    baseDifficulty: "mittel",
    baseDuration: 32,
    baseXp: 70,
    icon: "dumbbell",
    evidenceLevel: "evidenzbasiert",
    tags: ["praesentation", "harmonie", "koerperfett"],
    gymLevel: "fortgeschritten",
  },
  {
    id: "upper-body-pull-4x10",
    title: "Upper Body Pull 4x10 (Rudern + Klimmzug)",
    description: "Rueckenfokus mit voller Range of Motion zur Verbesserung von Haltung und Rueckendichte.",
    category: "gym",
    baseDifficulty: "mittel",
    baseDuration: 34,
    baseXp: 72,
    icon: "dumbbell",
    evidenceLevel: "evidenzbasiert",
    tags: ["haltung", "symmetrie", "praesentation"],
    gymLevel: "fortgeschritten",
  },
  {
    id: "lower-body-squat-5x5",
    title: "Lower Body Squat 5x5",
    description: "Schwere Kniebeugen fuer Unterkoerperkraft, Hormonantwort und stabile athletische Basis.",
    category: "gym",
    baseDifficulty: "schwer",
    baseDuration: 36,
    baseXp: 80,
    icon: "dumbbell",
    evidenceLevel: "evidenzbasiert",
    tags: ["koerperfett", "praesentation"],
    gymLevel: "profi",
  },
  {
    id: "lower-body-hinge-4x8",
    title: "Lower Body Hinge 4x8 (RDL)",
    description: "Hintere Kette mit kontrollierter Hueftbeugung trainieren fuer Gluteus und Hamstrings.",
    category: "gym",
    baseDifficulty: "mittel",
    baseDuration: 33,
    baseXp: 74,
    icon: "dumbbell",
    evidenceLevel: "evidenzbasiert",
    tags: ["koerperfett", "haltung"],
    gymLevel: "fortgeschritten",
  },
  {
    id: "full-body-complex-5r",
    title: "Full Body Komplex 5 Runden x 6 Wdh",
    description: "Ganzkoerper-Zirkel mit moderatem Gewicht fuer Kraftausdauer und hohe Trainingsdichte.",
    category: "gym",
    baseDifficulty: "schwer",
    baseDuration: 30,
    baseXp: 76,
    icon: "flame",
    evidenceLevel: "evidenzbasiert",
    tags: ["koerperfett", "praesentation"],
    gymLevel: "fortgeschritten",
  },
  {
    id: "chest-bench-5x5",
    title: "Chest Fokus: Bankdruecken 5x5",
    description: "Progressive Laststeigerung im Bankdruecken fuer Brustvolumen und Oberkoerperpraesenz.",
    category: "gym",
    baseDifficulty: "mittel",
    baseDuration: 28,
    baseXp: 68,
    icon: "dumbbell",
    evidenceLevel: "evidenzbasiert",
    tags: ["praesentation", "harmonie"],
    gymLevel: "fortgeschritten",
  },
  {
    id: "shoulders-ohp-5x5",
    title: "Shoulders Fokus: Overhead Press 5x5",
    description: "Vertikales Druecken zur Entwicklung der Schulterkappe und stabilen Rumpfspannung.",
    category: "gym",
    baseDifficulty: "mittel",
    baseDuration: 27,
    baseXp: 67,
    icon: "dumbbell",
    evidenceLevel: "evidenzbasiert",
    tags: ["praesentation", "symmetrie"],
    gymLevel: "fortgeschritten",
  },
  {
    id: "back-row-4x12",
    title: "Back Fokus: Rudern 4x12",
    description: "Horizontales Ziehen mit Fokus auf Schulterblattdepression fuer breite und dichte Rueckenoptik.",
    category: "gym",
    baseDifficulty: "mittel",
    baseDuration: 29,
    baseXp: 66,
    icon: "dumbbell",
    evidenceLevel: "evidenzbasiert",
    tags: ["haltung", "symmetrie", "praesentation"],
    gymLevel: "anfaenger",
  },
  {
    id: "arms-superset-3x12",
    title: "Arms Superset 3x12 + 3x12",
    description: "Bizeps und Trizeps im Superset fuer Armvolumen bei effizienter Trainingszeit.",
    category: "gym",
    baseDifficulty: "mittel",
    baseDuration: 24,
    baseXp: 60,
    icon: "dumbbell",
    evidenceLevel: "evidenzbasiert",
    tags: ["praesentation", "harmonie"],
    gymLevel: "anfaenger",
  },
  {
    id: "core-circuit-4r",
    title: "Core Circuit 4 Runden x 45s",
    description: "Antirotation, Flexion und Stabilisation fuer straffe Koerpermitte und bessere Lastuebertragung.",
    category: "gym",
    baseDifficulty: "mittel",
    baseDuration: 22,
    baseXp: 58,
    icon: "shield",
    evidenceLevel: "evidenzbasiert",
    tags: ["koerperfett", "praesentation"],
    gymLevel: "alle",
  },
  {
    id: "neck-strength-harness-3x15",
    title: "Neck Strength Harness 3x15",
    description: "Gezieltes Nackentraining mit kontrollierter Last fuer robustere Halsmuskulatur.",
    category: "gym",
    baseDifficulty: "mittel",
    baseDuration: 18,
    baseXp: 55,
    icon: "weight",
    evidenceLevel: "evidenzbasiert",
    tags: ["kinn", "harmonie", "praesentation"],
    gymLevel: "fortgeschritten",
  },
  {
    id: "grip-carry-crush-4x30s",
    title: "Grip Mix: Carry + Crush 4x30s",
    description: "Kombiniert statischen Griff und Crush-Grip fuer Unterarmkraft und funktionelle Stabilitaet.",
    category: "gym",
    baseDifficulty: "mittel",
    baseDuration: 17,
    baseXp: 52,
    icon: "hand",
    evidenceLevel: "evidenzbasiert",
    tags: ["praesentation", "haltung"],
    gymLevel: "alle",
  },
  {
    id: "hip-90-90-switch",
    title: "Hip 90/90 Switches 3x12",
    description: "Innen- und Aussenrotation der Huefte mobilisieren, um Kniebeugen und Gangbild zu verbessern.",
    category: "mobilitaet",
    baseDifficulty: "leicht",
    baseDuration: 10,
    baseXp: 28,
    icon: "rotate-3d",
    evidenceLevel: "evidenzbasiert",
    tags: ["haltung", "symmetrie"],
    gymLevel: "alle",
  },
  {
    id: "thoracic-open-book-12",
    title: "Thoracic Open Book 3x12",
    description: "Rotationsmobilitaet der Brustwirbelsaeule steigern fuer freiere Schulterbewegungen.",
    category: "mobilitaet",
    baseDifficulty: "leicht",
    baseDuration: 9,
    baseXp: 27,
    icon: "book-open",
    evidenceLevel: "evidenzbasiert",
    tags: ["haltung", "praesentation"],
    gymLevel: "alle",
  },
  {
    id: "hamstring-pnf-3x30",
    title: "Hamstring PNF 3x30s",
    description: "Wechsel aus Anspannung und Dehnung fuer bessere Hamstring-Laenge und Beckenkontrolle.",
    category: "mobilitaet",
    baseDifficulty: "mittel",
    baseDuration: 11,
    baseXp: 31,
    icon: "stretch-horizontal",
    evidenceLevel: "evidenzbasiert",
    tags: ["haltung", "koerperfett"],
    gymLevel: "alle",
  },
  {
    id: "hip-flexor-couch-stretch",
    title: "Hip Flexor Couch Stretch 3x60s",
    description: "Verkuerzte Hueftbeuger nach langem Sitzen loesen, um Hyperlordose zu entlasten.",
    category: "mobilitaet",
    baseDifficulty: "mittel",
    baseDuration: 10,
    baseXp: 30,
    icon: "armchair",
    evidenceLevel: "evidenzbasiert",
    tags: ["haltung", "praesentation"],
    gymLevel: "alle",
  },
  {
    id: "cat-cow-2x10",
    title: "Cat Cow 2x10",
    description: "Dynamische Wirbelsaeulenmobilisation zur Vorbereitung von Training oder langem Sitzen.",
    category: "mobilitaet",
    baseDifficulty: "leicht",
    baseDuration: 8,
    baseXp: 24,
    icon: "waves",
    evidenceLevel: "evidenzbasiert",
    tags: ["haltung", "schlaf"],
    gymLevel: "alle",
  },
  {
    id: "child-pose-lat-reach",
    title: "Child Pose mit Lat Reach 3x45s",
    description: "Ruecken und Latissimus in ruhiger Atmung dehnen fuer Entspannung und Schulterfreiheit.",
    category: "mobilitaet",
    baseDifficulty: "leicht",
    baseDuration: 9,
    baseXp: 25,
    icon: "moon",
    evidenceLevel: "evidenzbasiert",
    tags: ["schlaf", "haltung"],
    gymLevel: "alle",
  },
  {
    id: "shoulder-cars-6",
    title: "Shoulder CARs 3x6 je Seite",
    description: "Kontrollierte Gelenkkreise verbessern aktive Schulterkontrolle ueber die gesamte Range.",
    category: "mobilitaet",
    baseDifficulty: "mittel",
    baseDuration: 10,
    baseXp: 29,
    icon: "rotate-cw",
    evidenceLevel: "evidenzbasiert",
    tags: ["haltung", "symmetrie"],
    gymLevel: "alle",
  },
  {
    id: "ankle-knee-to-wall-3x12",
    title: "Ankle Knee-to-Wall 3x12",
    description: "Sprunggelenksmobilitaet fuer tiefe Kniebeugen, stabilen Schritt und bessere Belastungsverteilung.",
    category: "mobilitaet",
    baseDifficulty: "leicht",
    baseDuration: 8,
    baseXp: 24,
    icon: "footprints",
    evidenceLevel: "evidenzbasiert",
    tags: ["haltung", "koerperfett"],
    gymLevel: "alle",
  },
  {
    id: "morning-sunlight-walk",
    title: "Morning Sunlight Walk 15 Min",
    description: "Morgendliches Tageslicht stabilisiert den zirkadianen Rhythmus und erleichtert abendliches Einschlafen.",
    category: "lifestyle",
    baseDifficulty: "leicht",
    baseDuration: 15,
    baseXp: 30,
    icon: "sun",
    evidenceLevel: "evidenzbasiert",
    tags: ["schlaf", "praesentation", "augen"],
    gymLevel: "alle",
  },
  {
    id: "hydration-reminder-blocks",
    title: "Hydration Blocks 5x500ml",
    description: "Wasser ueber den Tag verteilt trinken statt abends nachholen, fuer konstante Performance.",
    category: "lifestyle",
    baseDifficulty: "leicht",
    baseDuration: 5,
    baseXp: 20,
    icon: "droplets",
    evidenceLevel: "evidenzbasiert",
    tags: ["hydration", "haut", "augen"],
    gymLevel: "alle",
  },
  {
    id: "protein-each-meal",
    title: "Protein pro Mahlzeit 30-40g",
    description: "Jede Hauptmahlzeit mit hochwertigem Protein planen, um Regeneration und Muskelaufbau zu sichern.",
    category: "lifestyle",
    baseDifficulty: "leicht",
    baseDuration: 6,
    baseXp: 26,
    icon: "utensils",
    evidenceLevel: "evidenzbasiert",
    tags: ["koerperfett", "harmonie"],
    gymLevel: "alle",
  },
  {
    id: "daily-walk-8k",
    title: "Daily Walk 8000 Schritte",
    description: "Alltagsbewegung konsequent erhoehen, um Koerperfettmanagement und Stressregulation zu verbessern.",
    category: "lifestyle",
    baseDifficulty: "leicht",
    baseDuration: 45,
    baseXp: 42,
    icon: "footprints",
    evidenceLevel: "evidenzbasiert",
    tags: ["koerperfett", "schlaf", "praesentation"],
    gymLevel: "alle",
  },
  {
    id: "meal-prep-2xweek",
    title: "Meal Prep 2x pro Woche",
    description: "Mahlzeiten vorbereiten, um spontane unpassende Entscheidungen und Kalorienueberschuss zu minimieren.",
    category: "lifestyle",
    baseDifficulty: "mittel",
    baseDuration: 30,
    baseXp: 40,
    icon: "chef-hat",
    evidenceLevel: "evidenzbasiert",
    tags: ["koerperfett", "hydration"],
    gymLevel: "alle",
  },
  {
    id: "meditation-breathing-10",
    title: "Meditation + Atmung 10 Min",
    description: "Langsame Nasenatmung und Achtsamkeit helfen bei Stresssenkung und besserem Schlafbeginn.",
    category: "lifestyle",
    baseDifficulty: "leicht",
    baseDuration: 10,
    baseXp: 28,
    icon: "brain",
    evidenceLevel: "evidenzbasiert",
    tags: ["schlaf", "harmonie"],
    gymLevel: "alle",
  },
  {
    id: "morning-cleanse",
    title: "Morgendliche Reinigung 60s",
    description: "Mildes Reinigen entfernt Nachtablagerungen, ohne die Hautbarriere unnoetig zu reizen.",
    category: "hautpflege",
    baseDifficulty: "leicht",
    baseDuration: 3,
    baseXp: 18,
    icon: "sparkles",
    evidenceLevel: "evidenzbasiert",
    tags: ["haut", "praesentation"],
    gymLevel: "alle",
  },
  {
    id: "evening-double-cleanse",
    title: "Abendliche Double Cleanse 2 Schritte",
    description: "Sonnenschutz und Schmutz zuerst loesen, danach wasserbasiert reinigen fuer klare Poren.",
    category: "hautpflege",
    baseDifficulty: "leicht",
    baseDuration: 6,
    baseXp: 23,
    icon: "shower-head",
    evidenceLevel: "evidenzbasiert",
    tags: ["haut", "praesentation"],
    gymLevel: "alle",
  },
  {
    id: "moisturizer-am-pm",
    title: "Moisturizer morgens + abends",
    description: "Feuchtigkeitsspendende Creme nach der Reinigung auftragen, um Barrierefunktion zu stabilisieren.",
    category: "hautpflege",
    baseDifficulty: "leicht",
    baseDuration: 4,
    baseXp: 20,
    icon: "droplet",
    evidenceLevel: "evidenzbasiert",
    tags: ["haut", "harmonie"],
    gymLevel: "alle",
  },
  {
    id: "spf-50-reapply",
    title: "SPF 50 Auftrag + Reapply",
    description: "Jeden Morgen ausreichend Sonnenschutz nutzen und bei Ausseneinsatz regelmaessig erneuern.",
    category: "hautpflege",
    baseDifficulty: "leicht",
    baseDuration: 4,
    baseXp: 24,
    icon: "sun",
    evidenceLevel: "evidenzbasiert",
    tags: ["haut", "augen", "praesentation"],
    gymLevel: "alle",
  },
  {
    id: "lip-care-night",
    title: "Lip Care nachts 1x",
    description: "Lippenpflege vor dem Schlafen zur Reduktion von Trockenheit und Rissen.",
    category: "hautpflege",
    baseDifficulty: "leicht",
    baseDuration: 2,
    baseXp: 14,
    icon: "heart",
    evidenceLevel: "evidenzbasiert",
    tags: ["haut", "harmonie"],
    gymLevel: "alle",
  },
  {
    id: "tongue-posture-awareness",
    title: "Zungenhaltung-Reminder 5x taeglich",
    description: "Zunge sanft am Gaumen platzieren und nasal atmen; kann Haltung und Mundruhe verbessern, strukturelle Veraenderungen sind jedoch nur begrenzt belegt.",
    category: "gesicht",
    baseDifficulty: "leicht",
    baseDuration: 5,
    baseXp: 16,
    icon: "message-circle",
    evidenceLevel: "optional",
    tags: ["kiefer", "kinn", "harmonie"],
    gymLevel: "alle",
  },
  {
    id: "chewing-habit-balanced",
    title: "Kaugewohnheit beidseitig 2x10 Min",
    description: "Bewusst gleichmaessig beidseitig kauen; kann muskulare Balance foerdern, eine knoecherne Formveraenderung ist wissenschaftlich nur eingeschraenkt abgesichert.",
    category: "gesicht",
    baseDifficulty: "leicht",
    baseDuration: 10,
    baseXp: 18,
    icon: "circle-dot",
    evidenceLevel: "optional",
    tags: ["kiefer", "symmetrie"],
    gymLevel: "alle",
  },
  {
    id: "jaw-relaxation-drill",
    title: "Jaw Relaxation Drill 3x2 Min",
    description: "Kiefer bewusst lockern, Zaehne entkoppeln und Zunge ruhen lassen; sinnvoll gegen Spannung, aber nicht als garantierte strukturelle Gesichtsveraenderung.",
    category: "gesicht",
    baseDifficulty: "leicht",
    baseDuration: 7,
    baseXp: 17,
    icon: "smile",
    evidenceLevel: "optional",
    tags: ["kiefer", "harmonie", "schlaf"],
    gymLevel: "alle",
  },
  {
    id: "facial-breathing-nasal",
    title: "Nasenatmung tagsueber 20 Min Fokus",
    description: "Nasenatmung trainieren, um Mundtrockenheit und Hyperventilation zu reduzieren; positive Effekte sind plausibel, starke strukturelle Gesichtsveraenderungen bleiben limitiert belegt.",
    category: "gesicht",
    baseDifficulty: "leicht",
    baseDuration: 20,
    baseXp: 22,
    icon: "wind",
    evidenceLevel: "optional",
    tags: ["kiefer", "harmonie", "schlaf"],
    gymLevel: "alle",
  },
  {
    id: "symmetry-photo-check",
    title: "Symmetrie-Check 1x Woche",
    description: "Neutrale Fotos unter gleichem Licht vergleichen und Trends beobachten; hilfreich fuer Wahrnehmung und Gewohnheiten, nicht als medizinischer Nachweis.",
    category: "gesicht",
    baseDifficulty: "leicht",
    baseDuration: 8,
    baseXp: 19,
    icon: "camera",
    evidenceLevel: "optional",
    tags: ["symmetrie", "praesentation", "harmonie"],
    gymLevel: "alle",
  },
  {
    id: "protein-target-1-8g",
    title: "Protein-Ziel 1.8g/kg erreichen",
    description: "Taegliches Protein nach Koerpergewicht planen, um Muskelaufbau und Saettigung zu unterstuetzen.",
    category: "ernaehrung",
    baseDifficulty: "mittel",
    baseDuration: 12,
    baseXp: 34,
    icon: "beef",
    evidenceLevel: "evidenzbasiert",
    tags: ["koerperfett", "praesentation"],
    gymLevel: "alle",
  },
  {
    id: "colorful-plate-2-meals",
    title: "Bunte Teller 2 Mahlzeiten taeglich",
    description: "Gemuese- und Mikronaehrstoffdichte steigern fuer Hautbild, Verdauung und Regeneration.",
    category: "ernaehrung",
    baseDifficulty: "leicht",
    baseDuration: 10,
    baseXp: 29,
    icon: "salad",
    evidenceLevel: "evidenzbasiert",
    tags: ["haut", "harmonie", "koerperfett"],
    gymLevel: "alle",
  },
  {
    id: "sleep-routine-fixed",
    title: "Feste Schlafroutine 7 Tage",
    description: "Konstante Schlafens- und Aufstehzeiten stabilisieren Hormonrhythmus und Erholung.",
    category: "schlaf",
    baseDifficulty: "mittel",
    baseDuration: 8,
    baseXp: 35,
    icon: "moon-star",
    evidenceLevel: "evidenzbasiert",
    tags: ["schlaf", "haut", "augen"],
    gymLevel: "alle",
  },
  {
    id: "no-screens-60m",
    title: "Digital Detox 60 Min vor Schlaf",
    description: "Bildschirmlicht und mentale Reize vor dem Schlaf reduzieren, um Einschlaflatenz zu verkuerzen.",
    category: "schlaf",
    baseDifficulty: "mittel",
    baseDuration: 60,
    baseXp: 38,
    icon: "smartphone-off",
    evidenceLevel: "evidenzbasiert",
    tags: ["schlaf", "augen", "harmonie"],
    gymLevel: "alle",
  },
  {
    id: "water-2-5l-tracker",
    title: "Wasserziel 2.5L tracken",
    description: "Taegliches Trinkziel dokumentieren, um Leistungsabfall und Kopfschmerzen durch Dehydrierung zu vermeiden.",
    category: "wasser",
    baseDifficulty: "leicht",
    baseDuration: 5,
    baseXp: 24,
    icon: "droplets",
    evidenceLevel: "evidenzbasiert",
    tags: ["hydration", "haut", "augen"],
    gymLevel: "alle",
  },
  {
    id: "electrolytes-after-sweat",
    title: "Elektrolyte nach starkem Schwitzen",
    description: "Nach hoher Schweissrate Natrium und Fluessigkeit auffuellen fuer schnellere Regeneration.",
    category: "wasser",
    baseDifficulty: "leicht",
    baseDuration: 6,
    baseXp: 26,
    icon: "glass-water",
    evidenceLevel: "evidenzbasiert",
    tags: ["hydration", "koerperfett"],
    gymLevel: "alle",
  },
  {
    id: "zone2-cardio-35m",
    title: "Zone-2 Cardio 35 Min",
    description: "Moderate Ausdauerarbeit mit niedriger bis mittlerer Herzfrequenz fuer Fettstoffwechsel und Erholung.",
    category: "cardio",
    baseDifficulty: "mittel",
    baseDuration: 35,
    baseXp: 52,
    icon: "heart-pulse",
    evidenceLevel: "evidenzbasiert",
    tags: ["koerperfett", "schlaf", "praesentation"],
    gymLevel: "alle",
  },
  {
    id: "hiit-bike-10x1",
    title: "HIIT Bike 10x1 Min",
    description: "Kurzintensive Intervalle mit aktiver Pause zur Verbesserung von VO2 und Kondition.",
    category: "cardio",
    baseDifficulty: "schwer",
    baseDuration: 24,
    baseXp: 60,
    icon: "bike",
    evidenceLevel: "evidenzbasiert",
    tags: ["koerperfett", "praesentation"],
    gymLevel: "fortgeschritten",
  },
  {
    id: "scalp-massage-5m",
    title: "Kopfhautmassage 5 Min",
    description: "Sanfte Massage kann lokale Durchblutung und Entspannung verbessern, vor allem als Pflegeroutine.",
    category: "haarpflege",
    baseDifficulty: "leicht",
    baseDuration: 5,
    baseXp: 20,
    icon: "sparkles",
    evidenceLevel: "evidenzbasiert",
    tags: ["haar", "praesentation"],
    gymLevel: "alle",
  },
  {
    id: "gentle-shampoo-cycle",
    title: "Mildes Shampoo im passenden Rhythmus",
    description: "Waschfrequenz an Kopfhauttyp anpassen, um Ueberfettung und Austrocknung auszubalancieren.",
    category: "haarpflege",
    baseDifficulty: "leicht",
    baseDuration: 6,
    baseXp: 21,
    icon: "shower-head",
    evidenceLevel: "evidenzbasiert",
    tags: ["haar", "haut", "harmonie"],
    gymLevel: "alle",
  },
  {
    id: "weekly-checkin-photos",
    title: "Fortschrittfotos 1x/Woche",
    description: "Standardisierte Fotos unter gleichem Licht helfen bei objektiver Verlaufskontrolle ueber Monate.",
    category: "fortschritt",
    baseDifficulty: "leicht",
    baseDuration: 10,
    baseXp: 32,
    icon: "camera",
    evidenceLevel: "evidenzbasiert",
    tags: ["praesentation", "symmetrie", "koerperfett"],
    gymLevel: "alle",
  },
  {
    id: "habit-review-sunday",
    title: "Wochenreview am Sonntag 20 Min",
    description: "Gewohnheiten evaluieren, Stolpersteine dokumentieren und naechste Woche realistisch planen.",
    category: "fortschritt",
    baseDifficulty: "mittel",
    baseDuration: 20,
    baseXp: 36,
    icon: "clipboard-list",
    evidenceLevel: "evidenzbasiert",
    tags: ["praesentation", "harmonie", "schlaf"],
    gymLevel: "alle",
  },
  {
    id: "lymph-drainage-5m",
    title: "Lymphatische Gesichtsmassage 5 Min",
    description: "Sanfte Streichungen von der Gesichtsmitte nach aussen koennen morgendliche Schwellung sichtbar reduzieren.",
    category: "gesichtsmassage",
    baseDifficulty: "leicht",
    baseDuration: 5,
    baseXp: 23,
    icon: "hand-heart",
    evidenceLevel: "evidenzbasiert",
    tags: ["harmonie", "symmetrie", "praesentation"],
    gymLevel: "alle",
  },
  {
    id: "masseter-release-3m",
    title: "Masseter Release 3x60s",
    description: "Leichter Druck auf Kaumuskulatur kann Spannung und Pressen reduzieren; nur schmerzfrei und kontrolliert ausfuehren.",
    category: "gesichtsmassage",
    baseDifficulty: "leicht",
    baseDuration: 6,
    baseXp: 22,
    icon: "hand",
    evidenceLevel: "evidenzbasiert",
    tags: ["kiefer", "harmonie", "kinn"],
    gymLevel: "alle",
  },
];

export const HABIT_DATABASE: HabitEntry[] = HABIT_TEMPLATES.flatMap((template) =>
  WEEK_VARIANTS.map((variant) => ({
    id: `${template.id}-w${variant.weekMin}`,
    title: `${template.title} - ${variant.label}`,
    description: `${template.description} Woche ${variant.weekMin} Fokus: saubere Ausfuehrung und regelmaessige Dokumentation.`,
    category: template.category,
    difficulty: getProgressedDifficulty(template.baseDifficulty, variant.difficultyDelta),
    durationMinutes: Math.max(1, Math.round(template.baseDuration * variant.durationFactor)),
    icon: template.icon,
    xp: template.baseXp + variant.xpBonus,
    evidenceLevel: template.evidenceLevel,
    tags: template.tags,
    gymLevel: template.gymLevel,
    weekMin: variant.weekMin,
  })),
);

export const getHabitsByTag = (tag: PersonalizationTag): HabitEntry[] => {
  return HABIT_DATABASE.filter((habit) => habit.tags.includes(tag));
};

export const getHabitById = (id: string): HabitEntry | undefined => {
  return HABIT_DATABASE.find((habit) => habit.id === id);
};
